v0.0.3 ⬇
- the tttt.js exports all the wrapped node:assert function making them available for assertions files.
- it also makes available some decoration, and interaction function of the Object [ tttt ]

a simple usage:

filename assertion/test1.js
code ⬇︎ ___________________________

import * as tttt from 'trythistrythat'

// test must export a default async function.
export default async ()=>{

    // Object [ tttt.output.describe() ] decoration function.
    // example how to format a description for the test. not required at all.
    await tttt.describe('testnumber1'.green(), 'assertion ->'.red(), 0)

    // Object [tttt.oki] wrapped node:assert->ok()
    // all the wrapped node:assert functions are promisified, so they return [AssertionError] if they fail.
    // the parameter passed to all test unit functions must be a function, async just if needed.
    let error = await tttt.oki(()=>{

        // return is required
        // all the property names are required and named the same as this example
        // all the property values are required too.
        return {

            expected: 5,
            actual: 10,
            error: 'could be anything you like'

        }
    })

    if( error instanceof Error ) {

        // Object [ tttt.output.failed() ] interaction function.
        // let know to the Object [tttt.output.failed] about the error happened, so then the process.exit with code 1
        tttt.failed( true )

        // trace the error out
        console.trace( error )
    }
}