v1.1.1 ADDED eslint APPLIED, UPDATED JSDoc ⇩
- the return statement given at these Object functions:
  - oki
  - deeeeep suites

  if set to:
      return {
        actual: 'it is required, it has the result of the tested function'
        expected: 'it is required, it has the result of the tested function'
        error: ❗ no longer required ❗
      }
    - if specified returns the message given
    - if not returns AssertionError